### ISSUE TITLE
I trained in Colab and get models, but how do I  test these models ?

### ISSUE THREAD

**Issue by kananmammad** [AryaAftab/LIGHT-SERNET#1]

**Comment by kananmammad** [comment]
@AryaAftab 
Hi, please help for test models

**Comment by AryaAftab** [comment]
@kananmammad 
Hi, kananmammad
The best model in 10 fold-cross validation was saved in TFLite format. You can use the TensorFlow lite tutorial in [this site](https://www.tensorflow.org/lite) to learn how to deploy your trained TensorFlow Lite model on edge devices such as mobile and Raspberry Pi. If you have more questions feel free and ask.

**Comment by kananmammad** [comment]
@AryaAftab I don't have Rasperry PI, I use Ubuntu 20.04.3 LTS
There is train model with code in your project, but there isn't test the model with code

```bash
python train.py -dn "IEMOCAP" \
                -id 7 \
                -at "impro" \
                -ln "cross_entropy" \
                -v 1 \
                -it "mfcc"
```

Please, tell me how do I test this model with code ?

**Comment by AryaAftab** [comment]
Inside the [train.py](https://github.com/AryaAftab/LIGHT-SERNET/blob/master/train.py) file, the desired model is evaluated in each fold after training, and confusion matrices were saved in [result](https://github.com/AryaAftab/LIGHT-SERNET/tree/master/result) folder. For a separate test, you can use the functions prepared in [tflite_evaluate.py](https://github.com/AryaAftab/LIGHT-SERNET/blob/5b13f3bdaa159522d54e2da13cf0d0d5e0b63859/tflite_evaluate.py#L1) to evaluate your model:

__Example:__
```python
from tflite_evaluate import evaluate_model

BuffX = ... # Your mfccs (size : (batch_size, n_frame, n_mfcc, 1))
BuffY = ... # Your Labels (size : (batch_size, ))

evaluate_model(best_modelname_float32, model_type="float32", test_audios=BuffX, test_labels=BuffY)
```
