### ISSUE TITLE
cannot run the IEMOCAP dataset on windows

### ISSUE THREAD

**Issue by nijaaouikhalil** [AryaAftab/LIGHT-SERNET#3]
Hello, could you show the data folder architecture so I understand the way you organised the dataset.
I kept getting errors to segment the data.
I extracted the IEMOCAP_full_release in the data folder the renamed it as IEMOCAP, however, I kept getting errors of files not found.

**Comment by AryaAftab** [comment]
Hello,
To avoid taking up too much storage space, folders containing video and dialog audio were removed, and the database structure is as follows (plotted by **tree** command with depth 3). If you encounter more problems, feel comfortable and state them again.
Of course, you must change the path separator ( "/" for Linux) to ( "\\" for Windows) anywhere needed

```bash
./IEMOCAP/
├── Session1
│   ├── dialog
│   │   └── EmoEvaluation
│   └── sentences
│       └── wav
├── Session2
│   ├── dialog
│   │   └── EmoEvaluation
│   └── sentences
│       └── wav
├── Session3
│   ├── dialog
│   │   └── EmoEvaluation
│   └── sentences
│       └── wav
├── Session4
│   ├── dialog
│   │   └── EmoEvaluation
│   └── sentences
│       └── wav
└── Session5
    ├── dialog
    │   └── EmoEvaluation
    └── sentences
        └── wav
```

**Comment by nijaaouikhalil** [comment]
Hello @AryaAftab, 
Thanks a lot for responding. 
I've changed the path separator also the  pattern in the read_dataset file (line 14) to '{}**.***\t(.*?)\t\[' because it wouldn't match as is
I have also changed the label in the same file to match the name of the wavefile. . ( was throwing file not found errors )
lable = label_format.format(wavename[4], wavename[:].replace("/", "\\"))
 and yet I still getting errors related to the segmentation step.
 Can you confrim that the current main version works ? 
 Thanks a lot

**Comment by AryaAftab** [comment]
you're welcome @nijaaouikhalil,
Yes, the program works properly. The screenshot below shows the correct operation of the function (on Linux).
Why did you change the pattern? You just need to change the path separator.
![Screenshot from 2022-05-25 00-30-53](https://user-images.githubusercontent.com/30603302/170122903-82f5b541-9902-4ceb-9bd0-d8fc54e101f8.png)

**Comment by nijaaouikhalil** [comment]
Thanks a lot for the quick reply.
I changed the label to the commented one here because otherwise the file doesn't exist.
also for the pattern I accounted for the F000 that follows the name of the wave file 
![image](https://user-images.githubusercontent.com/55817695/170124991-57e3b6fd-9b83-4c56-ae17-0947d64b8b37.png)
![image](https://user-images.githubusercontent.com/55817695/170125089-f6b319c3-41a5-4bc5-aa76-6e2d984cec3d.png)

**Comment by AryaAftab** [comment]
Don't mention it @nijaaouikhalil,
I think there is a problem with the iemocap_before_segment function in Windows OS. This problem does not exist in Linux OS. From the error, it can be concluded that there is a problem when extracting the filenames of txt (lines 32 to 39).

**Comment by nijaaouikhalil** [comment]
can you elaborate what should be the label , the filename and wavename at that stage ( I am not sure why you remove the last 5 characters)
label = label_format.format(wavename[4], wavename[:-5])

also what should the regex match ? my understanding is that it should match the first occurrence of the wave filename (Ses01F_impro01)  so we don't care about the (_F000) part .

**Comment by AryaAftab** [comment]
Assume you have a wav with Ses01F_impro01_F001.wav name:
Line 32 removes .wav from file:
```python
wavename = filename[:-4] ---> Output: Ses01F_impro01_F001
```
Our label format is :
```python
label_format = 'Session{}/dialog/EmoEvaluation/{}.txt'
```
In line 33, you separate session numbers and txt filename:
```python
wavename[4] ---> Output: 1
wavename[:-5] ---> Output: Ses01F_impro01
label = label_format.format(wavename[4], wavename[:-5]) ---> Output: 'Session1/dialog/EmoEvaluation/Ses01F_impro01.txt'
```
In the end, you find Ses01F_impro01_F001 in your text and extract your label(in this example: neu)

**Comment by nijaaouikhalil** [comment]
Thanks a lot @AryaAftab  I fixed it, turns out the issue was that I didn't delete the wave files inside the dialog folder and didn't escape them when reading the filenames.

**Comment by AryaAftab** [comment]
Think nothing of it @nijaaouikhalil,
If the repository was useful to you, thank you for your support by starring.

**Comment by STU-ECHO** [comment]
I dont konw why I cant train this model with windows and using 3080, always raise type valueError
![image](https://user-images.githubusercontent.com/73876331/175933775-76848809-ccc6-4fa0-b158-14288e57f5f3.png)
and I run this exactly  in colab raise the same error when i do in the pycharm

**Comment by STU-ECHO** [comment]
> I dont konw why I cant train this model with windows and using 3080, always raise type valueError ![image](https://user-images.githubusercontent.com/73876331/175933775-76848809-ccc6-4fa0-b158-14288e57f5f3.png) and I run this exactly in colab raise the same error when i do in the pycharm

I solve the problem,and the reason is I made some mistakes with the [contents]

**Comment by AryaAftab** [comment]
Hi @STU-ECHO,
I was trying to debug your problem, but fortunately, you solved the problem yourself.
If the repository was useful to you, thank you for your support by starring.

**Comment by FLFLYBS** [comment]
@AryaAftab 
Hello, I can't find the file when I run “python train.py -dn "IEMOCAP" -id 7 -at "all" -ln "focal" -v 1 -it "mfcc" -c "disk" -m false”. I want to ask what may be the reason
![image](https://user-images.githubusercontent.com/45502388/195984281-04430d84-2b66-4b1f-abe8-ac83e38d6e3c.png)

**Comment by AryaAftab** [comment]
Hi @He-jia-wen 
The problem created for you in the previous question was created for someone else. Did you read the previous questions and answers?

**Comment by FLFLYBS** [comment]
> Hi @He-jia-wen The problem created for you in the previous question was created for someone else. Did you read the previous questions and answers?

Yes, I have read the previous question. It seems that this question is' - 'and' _ ' I modified the code myself, but there is a new question I want to ask
![image](https://user-images.githubusercontent.com/45502388/195994773-142ffb58-0e33-4665-bbd5-de9687128dcc.png)

**Comment by AryaAftab** [comment]
@He-jia-wen 
I did not understand what exactly your question is. Your error says "you don't have the Ses01M_script02_0.txt file". Are you sure you didn't delete the label files or change their directory?

**Comment by He-jia-wen** [comment]
> @He-jia-wen I did not understand what exactly your question is. Your error says "you don't have the Ses01M_script02_0.txt file". Are you sure you didn't delete the label files or change their directory?
> 
> By my checking, there is no file named Ses01M_script02_0.txt at all. How did you change the code? (of course, there is Ses01M_script02.txt)

yes. I only changed the path of the data, and then '-' and '_' appeared in the file name I added this line to the code,
![image](https://user-images.githubusercontent.com/45502388/196013084-e972510e-0497-4d12-92f1-cecaf41fb4f7.png)
The first problem I raised was solved by joining this industry
![image](https://user-images.githubusercontent.com/45502388/196013098-2782c806-aca9-4d29-b76a-5ac9aa378112.png)
Because the txt file name only includes' _ ', Exclude '-' (only included in wav file name)
Then the problem arises
![image](https://user-images.githubusercontent.com/45502388/196013136-8cda3c1c-242e-429e-a137-a591829c828f.png)
![image](https://user-images.githubusercontent.com/45502388/196013154-956fb863-1849-48b2-b3e1-f53bdddd5f80.png)
That is, the last character at the end of the file name is named from 1, not from 0 if an error is reported. After that, my code is directly cloned, so I asked you what problems might occur to cause this phenomenon, because when you answered other people's questions, you pointed out that you only need to modify the data path

**Comment by ttrikn** [comment]
> > I dont konw why I cant train this model with windows and using 3080, always raise type valueError ![image](https://user-images.githubusercontent.com/73876331/175933775-76848809-ccc6-4fa0-b158-14288e57f5f3.png) and I run this exactly in colab raise the same error when i do in the pycharm
> 
> I solve the problem,and the reason is I made some mistakes with the [contents]

Hello,I meet the same problem with you,How did you solve it exactly in the end?
![dcc6a51885071b37329577dbcf97a77](https://user-images.githubusercontent.com/105933472/201357150-8381a69f-106e-45be-90c3-d9e819db1b9f.png)

**Comment by chengming1108** [comment]
> 

how to fix it  i meet the same mis please~

**Comment by chengming1108** [comment]
> Hello,I meet the same problem with you,How did you solve it exactly in the end?

Hello,I meet the same problem with you,How did you solve it exactly in the end?
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/43940238/205911873-08d48023-cd27-4ff9-97f2-9292e9c56b69.png">

**Comment by chengming1108** [comment]
> > I dont konw why I cant train this model with windows and using 3080, always raise type valueError ![image](https://user-images.githubusercontent.com/73876331/175933775-76848809-ccc6-4fa0-b158-14288e57f5f3.png) and I run this exactly in colab raise the same error when i do in the pycharm
> 
> I solve the problem,and the reason is I made some mistakes with the [contents]
how to fix?? thanks for reply
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/43940238/205912098-31a6b882-132d-4976-b0b9-845fe92157f0.png">

**Comment by chengming1108** [comment]
> you're welcome @nijaaouikhalil, Yes, the program works properly. The screenshot below shows the correct operation of the function (on Linux). Why did you change the pattern? You just need to change the path separator. ![Screenshot from 2022-05-25 00-30-53](https://user-images.githubusercontent.com/30603302/170122903-82f5b541-9902-4ceb-9bd0-d8fc54e101f8.png)

hey tanks  for great job 
i have some ques for this
tensorflow.python.framework.errors_impl.InvalidArgumentError: Value for attr 'Tindices' of double is not in the list of allowed values: int32, int64
        ; NodeDef: {{node GatherV2}}; Op<name=GatherV2; signature=params:Tparams, indices:Tindices, axis:Taxis -> output:Tparams; attr=batch_dims:int,default=0; attr=Tparams:type; attr=Tindices:type,allowed=[DT_INT32, DT_INT64]; attr=Taxis:type,allowed=[DT_INT32, DT_INT64]> [Op:GatherV2]
<img width="1476" alt="image" src="https://user-images.githubusercontent.com/43940238/205913237-0241cbf2-3b02-4684-9cfc-1346ce7c47ad.png">

my tensor version is tensorflow                2.4.0rc0

**Comment by STU-ECHO** [comment]
> > > I dont konw why I cant train this model with windows and using 3080, always raise type valueError ![image](https://user-images.githubusercontent.com/73876331/175933775-76848809-ccc6-4fa0-b158-14288e57f5f3.png) and I run this exactly in colab raise the same error when i do in the pycharm
> > 
> > 
> > I solve the problem,and the reason is I made some mistakes with the [contents]
> > how to fix?? thanks for reply
> 
> <img alt="image" width="1420" src="https://user-images.githubusercontent.com/43940238/205912098-31a6b882-132d-4976-b0b9-845fe92157f0.png">

I feel sorry Cause I totally forget how I solve the problem,and unfortunately ,those code are saved in another PC which in a location I cant reach recently .I do have a little memorary semms that one of the audio file went wrong from session1,(the name of the file is wrong,).delete it. Hope its a memory from this code,maybe you can check it

**Comment by STU-ECHO** [comment]
> 



> > > > I dont konw why I cant train this model with windows and using 3080, always raise type valueError ![image](https://user-images.githubusercontent.com/73876331/175933775-76848809-ccc6-4fa0-b158-14288e57f5f3.png) and I run this exactly in colab raise the same error when i do in the pycharm
> > > 
> > > 
> > > I solve the problem,and the reason is I made some mistakes with the [contents]
> > > how to fix?? thanks for reply
> > 
> > 
> > <img alt="image" width="1420" src="https://user-images.githubusercontent.com/43940238/205912098-31a6b882-132d-4976-b0b9-845fe92157f0.png">
> 
> I feel sorry Cause I totally forget how I solve the problem,and unfortunately ,those code are saved in another PC which in a location I cant reach recently .I do have a little memorary semms that one of the audio file went wrong from session1,(the name of the file is wrong,).delete it. Hope its a memory from this code,maybe you can check it

Seems like its the IEMOCAP‘s directory have to be same with author's ,"https://github.com/AryaAftab/LIGHT-SERNET/issues/3#issuecomment-1132817523",those are my Memory fragments，try weather if it works

**Comment by chengming1108** [comment]
> Thanks a lot @AryaAftab I fixed it, turns out the issue was that I didn't delete the wave files inside the dialog folder and didn't escape them when reading the filenames.

hey，I'm so excited that you can reply me.Iam Chinese but my English is poor.I am try to solve the problem,can I have you wechat . I wanna discuss technology. My Wechat number is CM995958609

**Comment by chengming1108** [comment]
> you're welcome @nijaaouikhalil,
> Yes, the program works properly. The screenshot below shows the correct operation of the function (on Linux).
> Why did you change the pattern? You just need to change the path separator.

i fix it。is a fool question，thanks you reply 。Have a good day
