### ISSUE TITLE
About the license for this model

### ISSUE THREAD

**Issue by PINTO0309** [AryaAftab/LIGHT-SERNET#5]
Thank you for sharing your great code. smiley_cat

What is the license for this model? I'd like to cite it to the repository I'm working on if possible, but I want to post the license correctly.

https://github.com/PINTO0309/PINTO_model_zoo/tree/main/382_Light-SERNet

Thank you.

**Comment by AryaAftab** [comment]
Hi dear @PINTO0309,
I am glad that my codes are of interest to you, I used the MIT license for my models.

**Comment by PINTO0309** [comment]
Thanks! 👍
